#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/hdobbydesk/hdobbydesk /usr/bin/hdobbydesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/hdobbydesk.service ]; then
			rm /etc/systemd/system/hdobbydesk.service /usr/lib/systemd/system/hdobbydesk.service /usr/lib/systemd/user/hdobbydesk.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/hdobbydesk/files/systemd/hdobbydesk.service /usr/lib/systemd/system/hdobbydesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload hdobbydesk.service: Unit hdobbydesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/hdobbydesk.service:10: Executable path is not absolute: pkill -f "hdobbydesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/hdobbydesk.service
		fi
		systemctl daemon-reload
		systemctl enable hdobbydesk
		systemctl start hdobbydesk
	fi
fi
